#!/usr/bin/env node
/**
 * Emit dist/sw.js: a hand-rolled service worker precaching the entire built
 * bundle (design D1-D3 of add-offline-support). The asset list is derived by
 * walking dist/, so it cannot drift from the real output; the cache name is
 * derived from a hash of every listed file's contents, so any redeploy with
 * different bytes yields a new cache and triggers the update cycle.
 *
 * Runs after `vite build`; check-precache.mjs verifies the result.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const DIST = new URL("../dist/", import.meta.url).pathname;

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      yield* walk(path);
    } else {
      yield path;
    }
  }
}

let files;
try {
  files = [...walk(DIST)].map((file) => relative(DIST, file)).sort();
} catch {
  console.error("generate-sw: dist/ not found — run `vite build` first.");
  process.exit(1);
}

const hash = createHash("sha256");
for (const file of files) {
  hash.update(file);
  hash.update(readFileSync(join(DIST, file)));
}
const version = hash.digest("hex").slice(0, 16);

// URLs as the browser will request them: "/" for index.html, "/path" otherwise.
// dist paths use the platform separator; URLs always use "/".
const urls = files.map((file) => (file === "index.html" ? "/" : `/${file.split(sep).join("/")}`));

const sw = `/* Generated by scripts/generate-sw.mjs — do not edit or commit. */
const CACHE = "memo-army-dev-${version}";
const ASSETS = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name))),
    ),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) {
    return;
  }
  // Navigations always get the cached shell; hashed assets are cache-first.
  const target = request.mode === "navigate" ? "/" : request;
  event.respondWith(
    caches.match(target, { cacheName: CACHE }).then((cached) => cached ?? fetch(request)),
  );
});
`;

writeFileSync(join(DIST, "sw.js"), sw);
console.log(`generate-sw: OK (${urls.length} assets precached, cache memo-army-dev-${version})`);
