#!/usr/bin/env node
/**
 * Emit dist/sw.js: a hand-rolled service worker precaching the entire built
 * bundle (design D1-D3 of add-offline-support). The asset list is derived by
 * walking dist/, so it cannot drift from the real output; the cache name is
 * derived from a hash of every listed file's contents, so any redeploy with
 * different bytes yields a new cache and triggers the update cycle.
 *
 * Runs after `vite build`; check-precache.mjs verifies the result.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const DIST = new URL("../dist/", import.meta.url).pathname;

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      yield* walk(path);
    } else {
      yield path;
    }
  }
}

let files;
try {
  files = [...walk(DIST)].map((file) => relative(DIST, file)).sort();
} catch {
  console.error("generate-sw: dist/ not found — run `vite build` first.");
  process.exit(1);
}

const hash = createHash("sha256");
for (const file of files) {
  hash.update(file);
  hash.update(readFileSync(join(DIST, file)));
}
const version = hash.digest("hex").slice(0, 16);

// URLs as the browser will request them: "/" for index.html, "/path" otherwise.
// dist paths use the platform separator; URLs always use "/".
const urls = files.map((file) => (file === "index.html" ? "/" : `/${file.split(sep).join("/")}`));

const sw = `/* Generated by scripts/generate-sw.mjs — do not edit or commit. */
const CACHE = "memo-army-dev-${version}";
const ASSETS = ${JSON.stringify(urls, null, 2)};

// Precache with addAll's all-or-nothing semantics, but strip the redirect
// flag first (design D1/D2 of fix-sw-redirected-responses): hosts like
// Cloudflare 308 .html URLs to pretty URLs, and a stored response carrying
// the redirect flag may never answer a navigation (WebKit: "Response served
// by service worker has redirections").
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      Promise.all(
        ASSETS.map(async (url) => {
          const response = await fetch(url);
          if (!response.ok) {
            throw new Error("precache failed: " + url + " (" + response.status + ")");
          }
          const clean = response.redirected
            ? new Response(await response.blob(), {
                status: response.status,
                statusText: response.statusText,
                headers: response.headers,
              })
            : response;
          await cache.put(url, clean);
        }),
      ),
    ),
  );
});

// Update promotion (design D2 of add-sw-update-button): the page posts
// SKIP_WAITING from the update button's click handler; nothing else may
// promote a waiting worker.
self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name))),
    ),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) {
    return;
  }
  // Navigations get the cached page for either URL form — exact precached
  // path or its pretty (extensionless) alias, e.g. /acknowledgements for
  // /acknowledgements.html (design D3 of fix-sw-redirected-responses) — and
  // the app shell otherwise; hashed assets are cache-first.
  const path = new URL(request.url).pathname;
  const target =
    request.mode === "navigate"
      ? ASSETS.includes(path)
        ? path
        : ASSETS.includes(path + ".html")
          ? path + ".html"
          : "/"
      : request;
  event.respondWith(
    caches.match(target, { cacheName: CACHE }).then((cached) => cached ?? fetch(request)),
  );
});
`;

writeFileSync(join(DIST, "sw.js"), sw);
console.log(`generate-sw: OK (${urls.length} assets precached, cache memo-army-dev-${version})`);
